import './globals.css'
import "@radix-ui/themes/styles.css";
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'

const inter = Inter({ 
  subsets: ['latin'],
  display: "swap",
	variable: "--font-inter", 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.variable}>
        <Theme>
          <NavBar/>
          <main className='p-5'>
            <Container>{children}</Container>
          </main>
        </Theme>
      </body>
    </html>
  )
}